-- Extend the existing MySQL enum before using submission notifications.
ALTER TABLE email_notifications MODIFY COLUMN event_type ENUM(
    'ONBOARDING_INVITATION', 'ONBOARDING_CHANGES_REQUESTED', 'ONBOARDING_SUBMITTED',
    'CYCLE_PUBLISHED', 'ASSESSMENT_READY', 'ASSESSMENT_REOPENED', 'RESULT_PUBLISHED',
    'REMINDER', 'PASSWORD_CHANGED', 'MANUAL') NOT NULL;
