ALTER TABLE lookup_values
    ADD COLUMN IF NOT EXISTS requirement_type VARCHAR(20) NULL AFTER description;

INSERT INTO lookup_types (code, name, description, is_active, created_on, updated_on)
SELECT seed.code, seed.name, seed.description, 1, NOW(6), NOW(6)
FROM (
    SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE' AS code,
           'Employee Onboarding Documents - Onsite' AS name,
           'Documents used for onsite employee onboarding' AS description
    UNION ALL
    SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE',
           'Employee Onboarding Documents - Offshore',
           'Documents used for offshore employee onboarding'
) seed
WHERE NOT EXISTS (
    SELECT 1 FROM lookup_types existing WHERE UPPER(existing.code) = seed.code
);

INSERT INTO lookup_values
    (lookup_type_id, code, name, description, requirement_type,
     display_order, is_active, created_on, updated_on)
SELECT type_row.id, seed.code, seed.name, NULL, seed.requirement_type,
       seed.display_order, 1, NOW(6), NOW(6)
FROM lookup_types type_row
JOIN (
    SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE' type_code, 'RESUME' code, 'Resume' name, 'REQUIRED' requirement_type, 1 display_order
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'PHOTO_ID', 'Government Photo ID', 'REQUIRED', 2
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'I9', 'Form I-9', 'REQUIRED', 3
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'I9_SUPPORTING_DOCUMENT', 'I-9 Supporting Document', 'REQUIRED', 4
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'W4', 'Form W-4', 'REQUIRED', 5
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'DIRECT_DEPOSIT', 'Direct Deposit / Bank Details', 'REQUIRED', 6
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'OFFER_LETTER', 'Signed Offer Letter', 'REQUIRED', 7
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'EMPLOYMENT_AGREEMENT', 'Employment Agreement', 'CONDITIONAL', 8
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'NDA', 'NDA / Confidentiality Agreement', 'CONDITIONAL', 9
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'PASSPORT', 'Passport', 'CONDITIONAL', 10
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'VISA_COPY', 'Visa Copy', 'CONDITIONAL', 11
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'I797', 'I-797 Approval Notice', 'CONDITIONAL', 12
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'I94', 'I-94', 'CONDITIONAL', 13
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'EAD', 'Employment Authorization Document', 'CONDITIONAL', 14
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'SSN_COPY', 'Social Security Card Copy', 'CONDITIONAL', 15
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'STATE_TAX_FORM', 'State Withholding Form', 'CONDITIONAL', 16
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'EDUCATION_CERTIFICATES', 'Education Certificates', 'OPTIONAL', 17
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_ONSITE', 'BACKGROUND_CHECK', 'Background Verification Document', 'CONDITIONAL', 18
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'RESUME', 'Resume', 'REQUIRED', 1
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'AADHAAR_CARD', 'Aadhaar Card', 'REQUIRED', 2
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'PAN_CARD', 'PAN Card', 'REQUIRED', 3
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'BANK_COPY', 'Bank Copy / Cancelled Cheque', 'REQUIRED', 4
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'OFFER_LETTER', 'Signed Offer Letter', 'REQUIRED', 5
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'EMPLOYMENT_AGREEMENT', 'Employment Agreement', 'CONDITIONAL', 6
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'NDA', 'NDA / Confidentiality Agreement', 'CONDITIONAL', 7
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'EDUCATION_CERTIFICATES', 'Education Certificates', 'REQUIRED', 8
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'EXPERIENCE_LETTERS', 'Experience Letters', 'CONDITIONAL', 9
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'RELIEVING_LETTER', 'Relieving Letter', 'CONDITIONAL', 10
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'PREVIOUS_PAYSLIPS', 'Previous Employer Payslips', 'OPTIONAL', 11
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'FORM_16', 'Previous Form 16', 'OPTIONAL', 12
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'PASSPORT', 'Passport', 'OPTIONAL', 13
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'ADDRESS_PROOF', 'Address Proof', 'CONDITIONAL', 14
    UNION ALL SELECT 'EMPLOYEE_ONBOARDING_DOCUMENTS_OFFSHORE', 'PROFILE_PHOTO', 'Profile / Passport Size Photo', 'OPTIONAL', 15
) seed ON seed.type_code = UPPER(type_row.code)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    requirement_type = VALUES(requirement_type),
    display_order = VALUES(display_order),
    is_active = VALUES(is_active);
