package com.rit.performance.service;

public enum EmailEventType {
    ONBOARDING_INVITATION,
    ONBOARDING_CHANGES_REQUESTED,
    ONBOARDING_SUBMITTED,
    CYCLE_PUBLISHED,
    ASSESSMENT_READY,
    ASSESSMENT_REOPENED,
    RESULT_PUBLISHED,
    REMINDER,
    PASSWORD_CHANGED,
    MANUAL
}
